### ISSUE TITLE
Passing by value, but can be done by reference

### ISSUE THREAD

**Issue by rbetik12** [VephoVandenberg/AgainMinecraftClone#2]
https://github.com/VephoVandenberg/AgainMinecraftClone/blob/911a69cacea183db58c77b6253cfdc83250eddb8/AgainMinecraftProject/src/modules/world/world.cpp#L78

**Comment by rbetik12** [comment]
Please check all methods in thath files, you can pass everything by reference to avoid unnessecary copies

**Comment by VephoVandenberg** [comment]
Gottcha, will do that as soon as possible.
